version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
      target: alembic

  thermostat:
    build:
      context: .
      dockerfile: Dockerfile
      target: thermostat
    volumes:
      - ./.thermostat_cache:/cache
    restart: always

  weather:
    build:
      context: .
      dockerfile: Dockerfile
      target: weather
    volumes:
      - ./.weather_cache:/cache
    restart: always

  database:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=home
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    restart: always

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"
    volumes:
      - ./.grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini 
    restart: always
    