{
 "title": "Thermostat",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, temperature_degc FROM thermostat_record ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Heating duration in selected period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) * 5 FROM thermostat_record WHERE consigne_degc > temperature_degc AND \"time\" > $__timeFrom() AND \"time\" < $__timeTo() "
    }
   ]
  },
  {
   "title": "Heating duration in last 24h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) * 5 FROM thermostat_record WHERE consigne_degc > temperature_degc AND time > now() - INTERVAL '1 day' AND time < now() "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", temperature_degc, consigne_degc FROM thermostat_record WHERE \"time\" > $__timeFrom() AND \"time\" < $__timeTo()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", humidity_percent FROM thermostat_record WHERE \"time\" > $__timeFrom() AND \"time\" < $__timeTo()"
    }
   ]
  }
 ]
}